### ISSUE TITLE
Update README.md file to show how to use the code 

### ISSUE THREAD

**Issue by ferid333** [Paller77/Caesar-Cipher#1]
Update README.md file to show how to use the code

**Comment by Paller77** [comment]
Done! Thanks for the feedback :D

**Comment by ferid333** [comment]
You are welcome. Can you follow me and give feedbacks. Thanks !

**Comment by ferid333** [comment]
Hello again

**Comment by ferid333** [comment]
I think we can be co-author for one project

**Comment by ferid333** [comment]
What do you think ?
